apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-app2
  name: springboot-app2
  namespace: demo-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app2
  template:
    metadata:
      labels:
        app: springboot-app2
    spec:
      containers:
      - name: my-springboot-app2
        image: 071913595299.dkr.ecr.us-east-1.amazonaws.com/springbootapp2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app2
    k8s-app: springboot-app2
  name: springboot-app2
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  type: LoadBalancer
  selector:
    app: springboot-app2
    apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-app
  name: springboot-app
  namespace: demo-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: my-springboot-app
        image: 776236128214.dkr.ecr.ap-south-1.amazonaws.com/springboot-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app
    k8s-app: springboot-app
  name: springboot-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: springboot-app
 # Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-app-ingress
  namespace: demo-ns
  labels:
    app: springboot-app
spec:
  rules:
    - http:
        paths:
          - path: /app1
            pathType: Prefix
            backend:
              service:
                name: springboot-app
                port:
                  number: 80        
