apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-app2
  name: springboot-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app2
  template:
    metadata:
      labels:
        app: springboot-app2
    spec:
      containers:
      - name: my-springboot-app2
        image: 071913595299.dkr.ecr.us-east-1.amazonaws.com/springbootapp2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app2
    k8s-app: springboot-app2
  name: springboot-app2
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  type: LoadBalancer
  selector:
    app: springboot-app2
