apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-app2
  name: springboot-app2
  namespace: demo-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app2
  template:
    metadata:
      labels:
        app: springboot-app2
    spec:
      containers:
      - name: my-springboot-app2
        image: 071913595299.dkr.ecr.us-east-1.amazonaws.com/springbootapp2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  namespace: demo-ns
  name: springboot-app2
  labels:
    app: springboot-app2
spec:
  type: NodePort
  selector:
    app: springboot-app2
  ports:
    - port: 80
      targetPort: 8085
---
    # Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-app-ingress
  namespace: demo-ns
  labels:
    app: springboot-app2
spec:
  rules:
    - http:
        paths:
          - path: /app1
            pathType: Prefix
            backend:
              service:
                name: springboot-app2
                port:
                  number: 80                    
